chat_model:
  init_args:
    model: gemini-2.5-flash
    model_provider: openai
    api_key: ${GEMINI_API_KEY}
    base_url: https://generativelanguage.googleapis.com/v1beta/openai/
  max_requests_per_minute: 500
  max_requests_per_day: 2000

image_generator:
  class_path: tools.ImageGeneratorNanobananaGoogleAPI
  init_args:
    api_key: ${GEMINI_API_KEY}
  max_requests_per_minute: 10
  max_requests_per_day: 500

video_generator:
  class_path: tools.VideoGeneratorVeoGoogleAPI
  init_args:
    api_key: ${GEMINI_API_KEY}
  max_requests_per_minute: 2
  max_requests_per_day: 10

working_dir: .working_dir/idea2video
